export enum ErrorTypes {
  // Basic HTTP Errors
  HTTP_BAD_REQUEST = 'HTTP_BAD_REQUEST',
  HTTP_UNAUTHORIZED = 'HTTP_UNAUTHORIZED',
  HTTP_FORBIDDEN = 'HTTP_FORBIDDEN',
  HTTP_NOT_FOUND = 'HTTP_NOT_FOUND',
  HTTP_INTERNAL_SERVER_ERROR = 'HTTP_INTERNAL_SERVER_ERROR',

  // App HTTP Errors
  INVALID_ZOD_REQUEST = 'INVALID_ZOD_REQUEST',
  INVALID_INVITATION_CODE = 'INVALID_INVITATION_CODE',
  EXPIRED_INVITATION_CODE = 'EXPIRED_INVITATION_CODE',
  INACTIVE_INVITATION_CODE = 'INACTIVE_INVITATION_CODE'
}
